[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/data/ipl.json"
  [headers.values]
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"
